# CASE STUDY ON SUPERVISED LEARNING

Check out!!!

1.Read the dataset into python environment

2.Do necessary preprocessing steps

3.Find out which classification model gives the best result to predict iris species

4.Randon Forest Classification method.

In [1]:
#importing modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Read the dataset into python environment

In [2]:
data=pd.read_excel("iris (1).xls")
data.head()

SL   SW   PL   PW Classification
0  5.1  3.5  1.4  0.2    Iris-setosa
1  4.9  3.0  1.4  0.2    Iris-setosa
2  NaN  3.2  1.3  0.2    Iris-setosa
3  4.6  3.1  1.5  0.2    Iris-setosa
4  5.0  3.6  1.4  0.2    Iris-setosa

In [3]:
data.tail()

SL   SW   PL   PW  Classification
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  NaN  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

In [4]:
data.columns

Index(['SL', 'SW', 'PL', 'PW', 'Classification'], dtype='object')

In [5]:
data.describe()

SL          SW          PL          PW
count  143.000000  144.000000  144.000000  150.000000
mean     5.855944    3.049306    3.756250    1.198667
std      0.828168    0.430644    1.761306    0.763161
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [3]:
#checking for null values
data.isnull().sum()

SL                7
SW                6
PL                6
PW                0
Classification    0
dtype: int64

In [4]:
#filling all the null values
df=data.fillna(value=0)
df.isnull().sum()

SL                0
SW                0
PL                0
PW                0
Classification    0
dtype: int64

# 2.Preprocessing steps

In [3]:
#preprocessing using labelencoder
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['Classification']=le.fit_transform(data['Classification'])
data.head()

SL   SW   PL   PW  Classification
0  5.1  3.5  1.4  0.2               0
1  4.9  3.0  1.4  0.2               0
2  NaN  3.2  1.3  0.2               0
3  4.6  3.1  1.5  0.2               0
4  5.0  3.6  1.4  0.2               0

In [4]:
x=data.drop("Classification",axis=1)
y=data["Classification"]

In [5]:
x.describe()

SL          SW          PL          PW
count  143.000000  144.000000  144.000000  150.000000
mean     5.855944    3.049306    3.756250    1.198667
std      0.828168    0.430644    1.761306    0.763161
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [5]:
#minmaxscaler method
from sklearn import preprocessing
min_max=preprocessing.MinMaxScaler(feature_range=(0,1))
x=min_max.fit_transform(x)
x=pd.DataFrame(x)
x.describe()

0           1           2           3
count  143.000000  144.000000  144.000000  150.000000
mean     0.432207    0.437211    0.467161    0.457778
std      0.230047    0.179435    0.298526    0.317984
min      0.000000    0.000000    0.000000    0.000000
25%      0.222222    0.333333    0.101695    0.083333
50%      0.416667    0.416667    0.567797    0.500000
75%      0.583333    0.541667    0.694915    0.708333
max      1.000000    1.000000    1.000000    1.000000

In [6]:
x=np.nan_to_num(x)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)
from sklearn import linear_model
lr=linear_model.LinearRegression()
model=lr.fit(x_train,y_train)
predictions=model.predict(x_test)
from sklearn.metrics import mean_squared_error
print("MSE is:",mean_squared_error(y_test,predictions))
from sklearn.metrics import r2_score
print("R squared value is:",r2_score(y_test,predictions))

MSE is: 0.030364094779773955
R squared value is: 0.9565537594566033


INSIGHT:
    
It suggest a strong positive correlation.

# 3.Classification Models

1.LINEAR REGRESSION MODEL

In [7]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [8]:
y_pred=model.predict(x_test)

In [10]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score
print("confusion matrix",confusion_matrix(y_pred,y_test))
print("Accuracy:",accuracy_score(y_pred,y_test)*100)
print("Precision:",precision_score(y_pred,y_test,average="macro")*100)
print("Recall:",recall_score(y_pred,y_test,average="macro")*100)
print("F1 score:",f1_score(y_pred,y_test,average="macro")*100)

confusion matrix [[10  1  0]
 [ 0  8  0]
 [ 0  0 11]]
Accuracy: 96.66666666666667
Precision: 96.29629629629629
Recall: 96.96969696969697
F1 score: 96.45191409897292


2.KNearestNeighbor

In [12]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier()
model.fit(x_train,y_train)

KNeighborsClassifier()

In [13]:
y_pred=model.predict(x_test)

In [14]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score
print("confusion matrix",confusion_matrix(y_pred,y_test))
print("Accuracy:",accuracy_score(y_pred,y_test))
print("Precision:",precision_score(y_pred,y_test,average="macro"))
print("Recall:",recall_score(y_pred,y_test,average="macro"))
print("F1 score:",f1_score(y_pred,y_test,average="macro"))

confusion matrix [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 score: 1.0


INSIGHT:
    
The f1 score and accuracy = 1 . so we can say that it is a good model of classification    

3.DECISION TREE MODEL

In [15]:
from sklearn.tree import DecisionTreeClassifier
dt_model=DecisionTreeClassifier()
dt_model.fit(x_train,y_train)

DecisionTreeClassifier()

In [16]:
y_pred=dt_model.predict(x_test)

In [17]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score
print("confusion matrix",confusion_matrix(y_pred,y_test))
print("Accuracy:",accuracy_score(y_pred,y_test))
print("Precision:",precision_score(y_pred,y_test,average="macro"))
print("Recall:",recall_score(y_pred,y_test,average="macro"))
print("F1 score:",f1_score(y_pred,y_test,average="macro"))

confusion matrix [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 score: 1.0


INSIGHT:

"DECISION TREE " is a good model of classification.

4.LINEAR SVM

In [18]:
from sklearn.svm import SVC
svm_linear=SVC(kernel='linear')
svm_linear.fit(x_train,y_train)

SVC(kernel='linear')

In [19]:
y_pred=svm_linear.predict(x_test)

In [20]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score
print("confusion matrix",confusion_matrix(y_pred,y_test))
print("Accuracy:",accuracy_score(y_pred,y_test))
print("Precision:",precision_score(y_pred,y_test,average="macro"))
print("Recall:",recall_score(y_pred,y_test,average="macro"))
print("F1 score:",f1_score(y_pred,y_test,average="macro"))

confusion matrix [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 score: 1.0


INSIGHT:

We can say that "linear svm" is a good model of classification.

5.POLYNOMIAL SVM

In [21]:
from sklearn.svm import SVC
svm_poly=SVC(kernel='poly',degree=3)
svm_poly.fit(x_train,y_train)

SVC(kernel='poly')

In [22]:
y_pred=svm_poly.predict(x_test)

In [23]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score
print("confusion matrix",confusion_matrix(y_pred,y_test))
print("Accuracy:",accuracy_score(y_pred,y_test))
print("Precision:",precision_score(y_pred,y_test,average="macro"))
print("Recall:",recall_score(y_pred,y_test,average="macro"))
print("F1 score:",f1_score(y_pred,y_test,average="macro"))

confusion matrix [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 score: 1.0


INSIGHT:

We can conclude that "polynomial svm" is a good model for our dataset.

# 4.Classification using RandomForest Classifier.

In [24]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train,y_train)

RandomForestClassifier()

In [25]:
y_pred=rf.predict(x_test)

In [26]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score
print("confusion matrix",confusion_matrix(y_pred,y_test))
print("Accuracy:",accuracy_score(y_pred,y_test))
print("Precision:",precision_score(y_pred,y_test,average="macro"))
print("Recall:",recall_score(y_pred,y_test,average="macro"))
print("F1 score:",f1_score(y_pred,y_test,average="macro"))

confusion matrix [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 score: 1.0


Insight:

f1 score value is 1. so we can conclude that it is a good model for our dataset

In [24]:
threshold=0.22
y_pred_prob=rf.predict_proba(x_test)[:,1]
y_pred=(y_pred_prob > threshold).astype(int)
f1_score(y_test,y_pred,pos_label='positive',average='micro')

C:\Users\ammus\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1295: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn("Note that pos_label (set to %r) is ignored when "


0.6333333333333333

In [17]:
rf.fit(x_train,y_train)
rft=RandomForestClassifier(n_estimators=500,max_depth=10,random_state=42,criterion="entropy")
rft.fit(x_train,y_train)


RandomForestClassifier(criterion='entropy', max_depth=10, n_estimators=500,
                       random_state=42)

In [20]:
y_pred=rft.predict(x_test)
f1_score(y_test,y_pred,pos_label='positive',average='micro')

C:\Users\ammus\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1295: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn("Note that pos_label (set to %r) is ignored when "


1.0